services:
  face-recognition:
    image: face-recognition:latest
    container_name: face-recognition
    network_mode: "host"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    working_dir: /usr/src/vision-app
    volumes:
      - ./data:/usr/src/vision-app/data
      - ./logs:/usr/src/vision-app/logs
      - ./:/usr/src/vision-app
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=$DISPLAY
    command: python examples/clients/korea.py
    ports:
      - 5003:5003
    env_file:
      - .env