services:
  face-recognition:
    image: face-recognition:latest
    volumes:
      - ./volumes/storage/face-recognition/data:/app/data
      - ./volumes/storage/face-recognition/logs:/app/logs
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - ${FR_PORT:-5000}:${FR_PORT:-5000}
    env_file:
      - .env