services:
  face-recognition-korea:
    image: face-recognition-korea:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: face-recognition-korea
    network_mode: "host"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    working_dir: /usr/src/vision-app
    volumes:
      - ./data:/usr/src/vision-app/data
      - ./logs:/usr/src/vision-app/logs
      - ./examples:/usr/src/vision-app/examples
      - ./src:/usr/src/vision-app/src
      - ./models:/usr/src/vision-app/models
      - ./configs:/usr/src/vision-app/configs
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: python examples/clients/korea.py
    ports:
      - 5003:5003
    env_file:
      - .env