[build-system]
requires = ["setuptools>=70.3.0,<80.0.0", "setuptools-scm>=8.0.4,<9.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "face_recognition"
authors = [{ name = "Mirsaid Abdurasulov", email = "abdurasulovm149@gmail.com" }]
description = "Our product is a face recognition system designed to detect, identify, and manage individuals using a secure database of face data."
readme = "README.md"
requires-python = ">3.9,<4.0"
keywords = [
	"face-recognition",
    "computer-vision",
	"artificial-intelligence",
	"machine-learning",
	"deep-learning",
]
license = { file = "LICENSE.txt" }
classifiers = [
	"Development Status :: 4 - Beta",
	"Intended Audience :: Developers",
	"Topic :: Software Development :: Libraries",
	"License :: OSI Approved :: MIT License",
	"Operating System :: OS Independent",
	"Programming Language :: Python :: 3.10",
]
dynamic = ["version", "dependencies"]

[tool.setuptools.packages.find]
where = ["src"]
include = ["face_recognition*", "person_tracking*"]
namespaces = false

[tool.setuptools.dynamic]
version = { attr = "face_recognition.__version__.__version__" }
dependencies = { file = "./requirements.txt" }