# Device settings
device: "cuda:1"  # Use GPU (CUDA) or switch to "cpu" if GPU is not available

# Database settings
db_path: "data/hb-kor"  # Path to the folder containing face images for recognition
output_video_path: "data/output.mp4"  # Path to save the output video with annotations

video_path: "videos/output_10.mkv"
# Camera input settings (RTSP links or video file paths)
in_camera: ""  # RTSP link or video file path for the entry camera
out_camera: ""  # RTSP link or video file path for the exit camera

# Database settings for recent entries
recent_entries_max_len: 3  # Maximum number of recent face entries to store for tracking

# Model configuration
model_path: "models/yolov8m-face.pt"  # Path to the face detection model
match_threshold: 0.7  # Threshold for face similarity matching
detection_threshold: 0.5  # Confidence threshold for face detection
imgsz: 960  # Image size for inference (higher values improve accuracy but increase processing time)
tracker: "bytetrack.yaml"  # Path to the tracker configuration file

# Video processing settings
skip_frames: 5  # Number of frames to skip between detections (reduces processing load)
