# Device settings
device: "cuda:0"  # Use GPU (CUDA) or switch to "cpu" if GPU is not available

# Database settings
db_path: "data/ilhan-aligned"  # Path to the folder containing face images for recognition
video_path: "videos/output_10.mkv"
output_video_path: "data/output.mp4"  # Path to save the output video with annotations

# Model configuration
model_path: "models/yolov8m-face.pt"  # Path to the face detection model
detection_threshold: 0.5  # Confidence threshold for face detection
imgsz: 1280  # Image size for inference (higher values improve accuracy but increase processing time)
tracker: "bytetrack.yaml"  # Path to the tracker configuration file

# SVM settings
svm_model_path: "models/svm_model.joblib"  # Path to the SVM model for face recognition
svm_label_path: "models/svm_labels.pkl"  # Path to the SVM labels for face recognition

# Face recognition settings
match_threshold: 0.6  # Threshold for face similarity matching
padding_ratio: 0.2  # Padding ratio for face cropping
align: True  # Enable face alignment
method: "cosine"  # Distance metric for face similarity matching (cosine, euclidean, manhattan)
layer: null # Feature extraction layer (layer0, layer16)
min_face_size: 30 # Minimum face size for detection

# Other settings
show: True  # Show the output video with annotations
save_video: True  # Save the output video with annotations
save_crops: False  # Save cropped face images for debugging
crops_path: "crops"  # Path to save cropped face images

# Evaluation settings
eval: False  # Enable evaluation mode

# ROI settings
roi: null  # Enable region of interest (ROI) mode
line_points: null # Define the ROI line points (e.g., [(0, 0), (1280, 720)])

# Timezone settings
timezone: "Asia/Seoul"  # Timezone for tracking times