# Device settings
device: "cuda:0"  # Use GPU (CUDA) or switch to "cpu" if GPU is not available

# Database settings
db_path: "data/ilhan-aligned"  # Path to the folder containing face images for recognition
video_path: "videos/output_10.mkv"
output_video_path: "data/output.mp4"  # Path to save the output video with annotations

# Model configuration
model_path: "models/yolov8m-face.pt"  # Path to the face detection model
detection_threshold: 0.5  # Confidence threshold for face detection
imgsz: 1280  # Image size for inference (higher values improve accuracy but increase processing time)
tracker: "bytetrack.yaml"  # Path to the tracker configuration file

# Face recognition settings
match_threshold: 0.6  # Threshold for face similarity matching
method: "cosine"  # Distance metric for face similarity matching (cosine, euclidean, manhattan)

# Other settings
show: True  # Show the output video with annotations
save_output: True  # Save the output video with annotations

# Evaluation settings
eval: False  # Enable evaluation mode

# ROI settings
roi: null  # Enable region of interest (ROI) mode
line_points: null # Define the ROI line points (e.g., [(0, 0), (1280, 720)])
