# Device settings
device: "cuda:0"  # Use GPU (CUDA) or switch to "cpu" if GPU is not available

# Database settings
db_path: "data/embeddings/hb-kor.pkl" # Must be in pkl format
video_path: "data/videos/sample.mp4"  # Path to the input video file or RTSP stream

# Face recognition settings
match_threshold: 0.3  # Threshold for face similarity matching

# Other settings
show: True  # Show the output video with annotations
save_video: True  # Save the output video with annotations

# Evaluation settings
eval: False  # Enable evaluation mode

# ROI settings
roi: null  # Enable region of interest (ROI) mode
line_points: null # Define the ROI line points (e.g., [(0, 0), (1280, 720)])

# Timezone settings
timezone: "Asia/Seoul"  # Timezone for tracking times
debug: True  # Enable debug mode for detailed logging
log_file: "logs/debug.log"  # Path to save the debug log file

# Database settings
host: "127.0.0.1"
name: "smart-office"
user: "postgres"
password: "hbvision"
port: 5432
path_to_db_config: "data/id/ilhan.json"
