services:
  ollama:
    restart: unless-stopped

  person-tracking:
    restart: unless-stopped
    environment:
      SO_LOG_LEVEL: DEBUG

  celery-worker:
    restart: unless-stopped
    environment:
      SO_LOG_LEVEL: DEBUG
