# Development overrides
# Usage: docker compose -f compose.yml -f template/compose/compose.dev.yml up

services:
  person-tracking:
    environment:
      PYTHONWARNINGS: "ignore::FutureWarning"
      SO_LOG_LEVEL: DEBUG
    volumes:
      - ./src:/app/src
      - ./configs:/app/configs
    restart: "no"
    tty: true
    stdin_open: true

  celery-worker:
    environment:
      PYTHONWARNINGS: "ignore::FutureWarning"
      SO_LOG_LEVEL: DEBUG
    volumes:
      - ./src:/app/src
      - ./configs:/app/configs

  flower:
    build:
      context: .
      dockerfile: Dockerfile.flower
    image: so.celery-flower
    container_name: lumiohub-celery-flower
    attach: false
    network_mode: host
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /app/src:/app
    depends_on:
      - celery-worker
    command: celery -A workers.celery_app.celery flower --port=${SO_FLOWER_PORT:-5555}
    working_dir: /app/src
    restart: "no"
